import { Product } from "./types/product";

// Liste des produits
export const PRODUCTS: Product[] = [
  {
    category: "Fruits",
    name: "Pommes",
    price: 1.50,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Fruits",
    name: "Poires",
    price: 1.60,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Fruits",
    name: "Bananes",
    price: 2.20,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Fruits",
    name: "Pêches",
    price: 1.95,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Fruits",
    name: "Fraises",
    price: 4.45,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Carottes",
    price: 2.45,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Poireaux",
    price: 2.99,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Courgettes",
    price: 1.98,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Tomates",
    price: 3.15,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Aubergines",
    price: 3.75,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Haricots verts",
    price: 2.50,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Choux",
    price: 1.59,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Salades",
    price: 1.50,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Légumes",
    name: "Radis",
    price: 2.55,
    instock: false,
    imageUrl: "",
  },
  {
    category: "Féculents",
    name: "Pâtes",
    price: 0.99,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Féculents",
    name: "Riz",
    price: 1.49,
    instock: true,
    imageUrl: "",
  },
  {
    category: "Féculents",
    name: "Semoule",
    price: 1.99,
    instock: false,
    imageUrl: "",
  },
];
